// .tw/164fc29fdde770c7/src/App.vue
<script setup>
import { computed, ref, watch } from 'vue'
import TaskForm from './components/TaskForm.vue'
import TaskList from './components/TaskList.vue'

const STORAGE_KEY = 'vue_vite_tasks_v1'

const tasks = ref(JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'))
const search = ref('')
const filter = ref('all')

watch(
  tasks,
  (value) => localStorage.setItem(STORAGE_KEY, JSON.stringify(value)),
  { deep: true },
)

const addTask = ({ title, note, priority }) => {
  tasks.value.unshift({
    id: crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`,
    title,
    note,
    priority,
    done: false,
    createdAt: Date.now(),
  })
}

const toggleTask = (id) => {
  tasks.value = tasks.value.map((t) => (t.id === id ? { ...t, done: !t.done } : t))
}

const deleteTask = (id) => {
  tasks.value = tasks.value.filter((t) => t.id !== id)
}

const stats = computed(() => {
  const total = tasks.value.length
  const done = tasks.value.filter((t) => t.done).length
  return { total, done, open: total - done }
})

const filteredTasks = computed(() => {
  const q = search.value.trim().toLowerCase()
  return tasks.value
    .filter((t) => {
      if (filter.value === 'open') return !t.done
      if (filter.value === 'done') return t.done
      return true
    })
    .filter((t) => {
      if (!q) return true
      return t.title.toLowerCase().includes(q) || t.note.toLowerCase().includes(q)
    })
})
</script>

<template>
  <main class="container">
    <header class="card">
      <h1>Vue Task Board</h1>
      <p class="muted">Vite + Vue (JavaScript) test app with localStorage persistence.</p>
      <div class="stats">
        <span>Total: {{ stats.total }}</span>
        <span>Open: {{ stats.open }}</span>
        <span>Done: {{ stats.done }}</span>
      </div>
    </header>

    <TaskForm @add-task="addTask" />

    <section class="card row">
      <input v-model="search" placeholder="Search tasks..." />
      <select v-model="filter">
        <option value="all">All</option>
        <option value="open">Open</option>
        <option value="done">Done</option>
      </select>
    </section>

    <TaskList :tasks="filteredTasks" @toggle-task="toggleTask" @delete-task="deleteTask" />
  </main>
</template>

// .tw/4230ddd54adccc49/src/App.tsx
import { useMemo, useState } from 'react'
import TaskForm from './components/TaskForm'
import TaskItem from './components/TaskItem'
import { loadTasks, saveTasks } from './lib/storage'
import type { Priority, Task } from './types'

type Filter = 'all' | 'open' | 'done'

function createId() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
}

export default function App() {
  const [tasks, setTasks] = useState<Task[]>(() => loadTasks())
  const [search, setSearch] = useState('')
  const [filter, setFilter] = useState<Filter>('all')
  const [priorityFilter, setPriorityFilter] = useState<'all' | Priority>('all')

  const updateTasks = (next: Task[]) => {
    setTasks(next)
    saveTasks(next)
  }

  const addTask = (title: string, description: string, priority: Priority) => {
    const next: Task[] = [
      {
        id: createId(),
        title,
        description,
        priority,
        done: false,
        createdAt: Date.now(),
      },
      ...tasks,
    ]
    updateTasks(next)
  }

  const toggleTask = (id: string) => {
    updateTasks(tasks.map((task) => (task.id === id ? { ...task, done: !task.done } : task)))
  }

  const deleteTask = (id: string) => {
    updateTasks(tasks.filter((task) => task.id !== id))
  }

  const filtered = useMemo(() => {
    return tasks
      .filter((task) => {
        if (filter === 'open') return !task.done
        if (filter === 'done') return task.done
        return true
      })
      .filter((task) => (priorityFilter === 'all' ? true : task.priority === priorityFilter))
      .filter((task) => {
        const q = search.trim().toLowerCase()
        if (!q) return true
        return task.title.toLowerCase().includes(q) || task.description.toLowerCase().includes(q)
      })
  }, [tasks, filter, priorityFilter, search])

  const stats = useMemo(() => {
    const total = tasks.length
    const done = tasks.filter((task) => task.done).length
    const open = total - done
    const high = tasks.filter((task) => task.priority === 'high').length
    return { total, open, done, high }
  }, [tasks])

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-8 text-slate-100">
      <div className="mx-auto max-w-5xl space-y-6">
        <header>
          <h1 className="text-3xl font-bold tracking-tight">PulseBoard</h1>
          <p className="text-slate-300">Task dashboard with search, filters, priority tags, and local persistence.</p>
        </header>

        <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Stat label="Total" value={stats.total} />
          <Stat label="Open" value={stats.open} />
          <Stat label="Done" value={stats.done} />
          <Stat label="High Priority" value={stats.high} />
        </section>

        <TaskForm onAdd={addTask} />

        <section className="grid gap-3 rounded-xl border border-slate-700 bg-slate-900/60 p-4 md:grid-cols-3">
          <input
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            placeholder="Search tasks..."
            className="rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100 outline-none focus:border-cyan-400"
          />
          <select
            value={filter}
            onChange={(event) => setFilter(event.target.value as Filter)}
            className="rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100 outline-none focus:border-cyan-400"
          >
            <option value="all">All tasks</option>
            <option value="open">Open only</option>
            <option value="done">Done only</option>
          </select>
          <select
            value={priorityFilter}
            onChange={(event) => setPriorityFilter(event.target.value as 'all' | Priority)}
            className="rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100 outline-none focus:border-cyan-400"
          >
            <option value="all">All priorities</option>
            <option value="low">Low only</option>
            <option value="medium">Medium only</option>
            <option value="high">High only</option>
          </select>
        </section>

        <section className="grid gap-3">
          {filtered.length === 0 ? (
            <div className="rounded-xl border border-slate-700 bg-slate-900/60 p-6 text-slate-300">
              No tasks match current filters.
            </div>
          ) : (
            filtered.map((task) => (
              <TaskItem key={task.id} task={task} onToggle={toggleTask} onDelete={deleteTask} />
            ))
          )}
        </section>
      </div>
    </main>
  )
}

function Stat({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-xl border border-slate-700 bg-slate-900/60 p-4">
      <p className="text-sm text-slate-300">{label}</p>
      <p className="text-2xl font-bold">{value}</p>
    </div>
  )
}
