// .tw/644e1c8e0bb95dae/src/App.tsx
import { useState } from "react"
import MetricCard from "./components/MetricCard"
import { averageExpense, expenses, totalExpense, type Expense } from "./lib/calc"
import "./App.css"

export default function App() {
  const [items, setItems] = useState<Expense[]>(expenses)
  const [label, setLabel] = useState("")
  const [amount, setAmount] = useState("")

  const addExpense = () => {
    const value = Number(amount)
    if (!label.trim() || !Number.isFinite(value) || value <= 0) return
    setItems(prev => [...prev, { id: Date.now(), label: label.trim(), amount: value }])
    setLabel("")
    setAmount("")
  }

  return (
    <main className="container">
      <h1>Expense Insights</h1>

      <section className="metrics">
        <MetricCard title="Total" value={`₹${totalExpense(items)}`} />
        <MetricCard title="Average" value={`₹${averageExpense(items)}`} />
        <MetricCard title="Entries" value={items.length} />
      </section>

      <section className="form">
        <input placeholder="Expense label" value={label} onChange={(e) => setLabel(e.target.value)} />
        <input placeholder="Amount" value={amount} onChange={(e) => setAmount(e.target.value)} />
        <button onClick={addExpense}>Add</button>
      </section>

      <ul className="list">
        {items.map((item) => (
          <li key={item.id}>
            <span>{item.label}</span>
            <strong>₹{item.amount}</strong>
          </li>
        ))}
      </ul>
    </main>
  )
}

// .tw/c7de056dbac289e0/src/App.vue
<script setup lang="ts">
import { computed, ref } from "vue"

type Expense = { id: number; label: string; amount: number }

const label = ref("")
const amount = ref("")
const list = ref<Expense[]>([
  { id: 1, label: "Hosting", amount: 1200 },
  { id: 2, label: "Email", amount: 700 },
])

const total = computed(() => list.value.reduce((sum, item) => sum + item.amount, 0))

function addExpense() {
  const v = Number(amount.value)
  const l = label.value.trim()
  if (!l || !Number.isFinite(v) || v <= 0) return
  list.value.push({ id: Date.now(), label: l, amount: v })
  label.value = ""
  amount.value = ""
}
</script>

<template>
  <main style="max-width: 700px; margin: 24px auto; padding: 0 16px;">
    <h1>Vue TS Expense Sheet</h1>
    <div style="display:flex; gap:8px;">
      <input v-model="label" placeholder="Label" />
      <input v-model="amount" placeholder="Amount" />
      <button @click="addExpense">Add</button>
    </div>
    <h3>Total: ₹{{ total }}</h3>
    <ul>
      <li v-for="item in list" :key="item.id">{{ item.label }} — ₹{{ item.amount }}</li>
    </ul>
  </main>
</template>
